name = "icavs-backend"
compatibility_date = "2024-01-01"

[env.production.vars]
# Add your environment variables here
NEON_DATABASE_URL = "postgresql://neondb_owner:npg_k6IqUTBJMC8S@ep-dawn-moon-ae8oofoc-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
CLERK_SECRET_KEY = "pk_test_bW9kZXJuLXBhcnJvdC05MS5jbGVyay5hY2NvdW50cy5kZXYk"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "29b04035e82a4126b2b502df277a7591"